Added MarshallableOutBuilder for file/http protocols
OpenHFT/Chronicle-Wire pull request #431
Opened 2022-04-12 15:08 UTC by peter-lawrey

2022-04-12 15:25 UTC, peter-lawrey commented
Note: this is just an HTTP Client, it should work with any HTTP server.

2022-04-12 15:49 UTC, RobAustin approved these changes

2022-04-13 05:36 UTC, JerryShea requested changes
needs to be rebased

2022-04-13 07:56 UTC, JerryShea approved these changes

2022-04-19 02:56 UTC, JerryShea approved these changes

2022-05-08 10:25 UTC, merged