Add leading zeros support for SymbolsLongConverter.
OpenHFT/Chronicle-Wire pull request #800
Opened 2024-01-02 17:31 UTC by yevgenp

Fixes #649

2024-01-02 17:33 UTC, yevgenp commented
It's a possible implementation option which comes with its' own drawbacks (maxLength -1, long overflow).

2024-03-20 03:59 UTC, nicktindall commented
Very clever. I like this approach better than https://github.com/OpenHFT/Chronicle-Wire/pull/822 because the latter still strips leading zeroes. If everyone's happy with the reduced max length, and we're certain that it's backwardly compatible then it's approved by me.

2024-03-20 03:59 UTC, nicktindall approved these changes

2024-03-20 03:59 UTC, nicktindall commented
Be good to get @peter-k-lawrey's thoughts on this one

2024-03-20 04:43 UTC, JerryShea commented
> Be good to get @peter-k-lawrey's thoughts on this one

What if he disagrees with @peter-lawrey ?

2024-03-20 04:44 UTC, nicktindall commented
> > Be good to get @peter-k-lawrey's thoughts on this one
> 
> What if he disagrees with @peter-lawrey ?

Is there a hierarchy of Peters? surely they don't always agree

2024-03-20 04:48 UTC, JerryShea commented
> > > Be good to get @peter-k-lawrey's thoughts on this one
> > 
> > 
> > What if he disagrees with @peter-lawrey ?
> 
> Is there a hierarchy of Peters? surely they don't always agree

Ask @peter-lawrey-admin - he surely is the boss

2024-03-20 04:58 UTC, nicktindall commented on src/main/java/net/openhft/chronicle/wire/converter/SymbolsLongConverter.java
> +
Actually this isn't backward or forward compatible. I really like it though, perhaps we make it a separate implementation and deprecate this one....

e.g. when encoded by the new impl and read by the old impl you get
`5HELLO`

and when encoded by the old impl and read by the new impl you get:
`ELLO`

2024-03-20 04:59 UTC, nicktindall requested changes
We should make this a separate implementation and deprecate the existing implementation, or even keep them as alternatives. It's not forward or backward coimpatible which is an issue if you have persisted data, or if you upgrade services that communicate independently.

2024-03-20 08:23 UTC, yevgenp commented
Already implemented in #822

2024-03-20 08:23 UTC, closed without merging