Support generateTuple being set for an individual WireIn, rather than global all or nothing.
OpenHFT/Chronicle-Wire pull request #823
Opened 2024-01-31 12:06 UTC by peter-lawrey

Tuples support reading data for a type you don't have locally and then passing it on by writing it.

2024-01-31 12:11 UTC, yevgenp approved these changes

2024-02-01 08:57 UTC, RobAustin approved these changes

2024-02-02 10:59 UTC, maxim-ponomarev requested changes
WireTypeConverter still doesn't handle unknown classes

2024-02-02 11:32 UTC, maxim-ponomarev commented
Added test (see above)

2024-02-02 13:52 UTC, maxim-ponomarev commented
Let me know, if I'm misusing Tuples and they are not supposed to retain the type information.

2025-10-17 08:47 UTC, peter-lawrey commented
Replaced by a newer PR

2025-10-17 08:47 UTC, closed without merging